### ISSUE TITLE
Cursor placement

### ISSUE THREAD

**Issue by FatherWh0** [Rayzr522/DecoHeads#1]
I'm not certain if you're in control of this but I've noticed when I click 'next page' the cursor jumps two blocks left to the center position making it a bit clunky to browse through the pages quickly.  If the cursor's position didn't change it would make it easier to scroll through pages.

Thx and sry to bother you over something petty. We do speed builds. Everything's in a hurry.

**Comment by foxfirecodes** [comment]
No, it's fine! It's not petty :P

Yes, I do know about the problem. No, I can't is it without rewriting the entire inventory system. I AM actually planning on doing that (even adding a category system) but I have other code I need to work on right now. The reason why it does this is because when it goes to the next page it closes the inventory, generates the next one, and then opens that. In between the two inventories your cursor resets back to the center of your screen because that's where it always is in-game. 

Just a tip, if you don't move your cursor at all after click next/previous it won't update and it'll think you're still on whatever slot you were on before.

**Comment by FatherWh0** [comment]
Yes, too much work for too little an issue, lol. Thx for the time to respond.

**Comment by foxfirecodes** [comment]
No problem! I will probably re-write the whole inventory system soon, but I've been putting off my other work.

Bye!
