### ISSUE TITLE
Plugin is abandoned. 

### ISSUE THREAD

**Issue by TheIntelloBox** [Rayzr522/DecoHeads#14]
?

**Comment by TheIntelloBox** [comment]
?

**Comment by foxfirecodes** [comment]
My life has become far crazier than I expected, and now I simply don't have the time to maintain this plugin. If I do ever get the time, I might come back and work on this again. But I've not only lost most of my free time, I've also lost my passion for Bukkit. Development in Bukkit is painful, and I honestly aught to just rewrite most of DecoHeads to be a little more flexible for future features. But rewriting an entire plugin is a long and difficult process, and I'm not sure if/when I will have the time to do that.

**Comment by TheIntelloBox** [comment]
Okay I understand. Could you just update the plugin when is a new version ? For example when there is 1.13, will you be able to update it please ?

**Comment by foxfirecodes** [comment]
The plugin should hopefully still work just fine when 1.13 comes out.

**Comment by TheIntelloBox** [comment]
Plugin is not abandoned ? :o Will you add new heads ?

**Comment by foxfirecodes** [comment]
I have very little time, but I'm trying to rewrite what I can. The first priority is to clean up the old code, then to add a playerdata system so I can implement economy support. I believe that was requested by both you and another user. (#11 #13)

I'm not making any promises, but we'll see what I can do. I'm also hoping to implement a command to add new heads from in-game, since I don't like the idea of people touching the heads.yml file. The format is too strange and I feel like people'll just break the plugin if they start messing around in heads.yml.

**Comment by foxfirecodes** [comment]
The plugin is no longer abandoned. I just added economy support, a settings editor and a head editor. (83cbf670806fd35ff7475f4a098d086c6045f7a1) I'll hopefully be ready for release soon, I believe the only thing left to do is #11.
