### ISSUE TITLE
Add Categories

### ISSUE THREAD

**Issue by TheIntelloBox** [Rayzr522/DecoHeads#3]
Hello,

Could you add categories for heads ?
For example, the category food, the category Pokemon, the category Social Network, Letter... :D

Thanks. :D

**Comment by foxfirecodes** [comment]
I will definitely attempt this, it's just that my UI code is very inflexible. If you aren't aware, I'm the owner of a development group called Perceive. I hate to do this, but I might start requiring PerceiveCore as a dependency since the GUI system in it would make my life 100x easier.

I actually wrote the GUI system so admittedly I'm kinda biased 😜

But anyways, first let me do #2. I can do that without PCore, and I'd like to avoid requiring it yet as it's not quite ready to be released.

**Comment by TheIntelloBox** [comment]
Okay fine. :D

**Comment by foxfirecodes** [comment]
So yeah this is a goal for v1.4, but I have to redo my GUI system's internals first, and that's gonna use Java 8. That's why I didn't make it part of v1.3.1, because I wanted to have a warning before switching to Java 8. 

Also it seems more appropriate to have a major version update for something as big as that :P (3 -> 4)

**Comment by TheIntelloBox** [comment]
Okay. :P So when, do you think ? xD

**Comment by foxfirecodes** [comment]
As soon as I finish up a little bit more on some other projects. I'll probably start the GUI rewrite later today.

**Comment by TheIntelloBox** [comment]
Oh okay, fine. :D

**Comment by foxfirecodes** [comment]
@TheIntelloBox 
Thought I might mention that I DID start the GUI rewrite, but it'll require some love before it's in a stable and release-worthy state.

**Comment by TheIntelloBox** [comment]
Oh okay, take your time. :D

**Comment by foxfirecodes** [comment]
That's a dangerous thing to tell me :wink:

**Comment by TheIntelloBox** [comment]
Me too. xD Where are you from ? xD

**Comment by foxfirecodes** [comment]
Earth 😄

**Comment by TheIntelloBox** [comment]
But please, where ? xD

**Comment by foxfirecodes** [comment]
`if (!me.knows(otherPerson)) {
  me.getLatestQuestion().respond(Reason.NOT_WILLING);
}`

:wink:

**Comment by TheIntelloBox** [comment]
xD. Java for ever ! :)

**Comment by foxfirecodes** [comment]
I'm from the US, and I just finished up this feature, so it'll be part of v1.4 which I will most likely release later today. If I don't release it today, I will release it tomorrow.

If you want the beta version you can [download it here](https://ci-perceive.rhcloud.com/job/DecoHeads/6/artifact/target/DecoHeads-1.4.jar).

**Comment by TheIntelloBox** [comment]
Fine !

With my head ? xD
