### ISSUE TITLE
Give Command

### ISSUE THREAD

**Issue by ARR4NN** [Rayzr522/DecoHeads#35]
A Command To /dh give <name> <head>
This will make it better for when making kits with decoheads in 

thanks

**Comment by foxfirecodes** [comment]
Please try [dev build 17](https://ci.rayzr.dev/job/DecoHeads/17/) and let me know if this does what you need!

`/dh give <head> [player]`

note that referencing heads in commands is now done by their "internal name", which is hyphenated rather than space-separated, allowing for easier tab completion. so for example instead of

```
/dh search Mossy Stone
```
it would now be
```
/dh search mossy-stone
```

**Comment by ARR4NN** [comment]
I have uploaded the new version and everything is working amazingly . Thanks so much for adding this feature . :)
possibly in the public version you could add a custom message like `&7[&9DecoHeads&7] &8You Were Given &2%item%` . 
Because currently its `command.decoheads.give.given` which dose not look amazing !
also will it work with placeholders like papi ones so `decoheads give apple %player%` ?
Other Than That Its Perfect And Will Make Adding Them To Kits 10 times easier !

**Comment by foxfirecodes** [comment]
the message is actually present but just needs to be added to your messages.yml. the easiest way to do this would be to delete your existing messages.yml and then it will generate a new one for you with that message.

as for whether it supports PlaceholderAPI placeholders, that's entirely up to whatever kits plugin you use.
