### ISSUE TITLE
Can't see decoheads

### ISSUE THREAD

**Issue by Zentriex** [Rayzr522/DecoHeads#36]
My fiance and I are playing in my server. The plugin works perfectly for her but all I see is steve's head please help

**Comment by foxfirecodes** [comment]
@anonplaguedoctor what server version are you playing? do you have the server in offline mode?

**Comment by Zentriex** [comment]
1.16.4 yes it is in offline mode but she can see it perfectly. Only I can't

**Comment by foxfirecodes** [comment]
i sorta suspect that offline mode is messing with this, since it messes with how skins & users and all that get resolved. i don't support offline mode so I can't help you much there, i'd suggest trying it in online mode if you are able to

you could also try just closing your game and reopening it, try different heads, try getting heads of regular users, etc. see if any of that works

**Comment by Zentriex** [comment]
Ight cool thanks man
________________________________
