### ISSUE TITLE
Mouse Cursor !

### ISSUE THREAD

**Issue by TheIntelloBox** [Rayzr522/DecoHeads#8]
Hello,

When we change page, the mouse cursor stays in the middle of the page.
So could you add a system, where the cursor is at the same position than the previous page ? :)
(For example, at the button Next Page, to be quickly).

Thanks ! :D

**Comment by foxfirecodes** [comment]
There's only one way to do that, but it might be possible with my new GUI system... I'll send you a dev build once I have it working.

The reason why the cursor position resets is, to change pages, the Inventory closes and then opens a new Inventory for the next/previous page. No way around that without changing the contents of the inventory, which I actually should be able to do now with my new GUI system.

**Comment by TheIntelloBox** [comment]
Okay. :( It's very important I think.

**Comment by foxfirecodes** [comment]
As I said, I should be able to do it with the new GUI system. Hopefully. Probably. Most likely. I think so 😜

**Comment by TheIntelloBox** [comment]
Okay. :D Fine. :)

**Comment by foxfirecodes** [comment]
@TheIntelloBox 
So we have a problem. The only way to keep the mouse cursor in place is by replacing the contents of the inventory instead of closing the inventory and opening a new one.

The problem with that? You can't change the title of the inventory without closing it and opening a new one. That means it doesn't change from "DecoHeads | Page 1".

So should I forget this issue? There is literally no way to change the title of the inventory, it's a fault in Minecraft itself (not even a fault in Bukkit).

The only alternative is to display the page number somewhere else.

**Comment by TheIntelloBox** [comment]
Oh, this is sad. :( But why in all Gui plugins, we haven't got the problem ?

**Comment by foxfirecodes** [comment]
The probably aren't trying to display a dynamic (changing) variable in the title of their GUIs :P

**Comment by TheIntelloBox** [comment]
Oh okay. xD

**Comment by foxfirecodes** [comment]
This will be fixed in v1.4 once I release it.
